[package]
name = "cfscrape"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"
description = "Wrapper for Python's cfscrape package."
license = "MIT"
readme = "README.md"

[dependencies]
pyo3 = "0.12"
